OCR/OCR/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OCR/core/urls.py
from django.urls import path
from . import views

app_name="core"
urlpatterns=[
    path("",views.index,name="index"),
]

OCR/core/models.py
from django.db import models

# Create your models here.

OCR/core/views.py
from django.shortcuts import render
import pytesseract
import numpy as np
from PIL import Image
import base64
pytesseract.pytesseract.tesseract_cmd = 'C:\Program Files\Tesseract-OCR\\tesseract.exe'
def index(request):
    if request.method=="POST":
        image=request.FILES["image"]
        image_data = base64.b64encode(image.read()).decode('utf-8')
        img = np.array(Image.open(image))
        
        text=pytesseract.image_to_string(img)
        return render(request, "core/index.html", {
            "ocr": text,
            "image":image_data})
    return render(request,"core/index.html")

OCR/core/templates/core/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OCR</title>
    <link rel="stylesheet" href="/static/style.css">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous"> 
    
</head>
<body>
    <header>
        <div class="heading">
            ocr
        </div>
    </header>
    <section class="main-body">
        <div class="title-desc">
            <h3 class="text" id="title">Scan It</Scan></h3>
            <h1 class="text" id="desc">< Scan and extract text from an image with Ease!></h1>
        </div>
    </section>
        
        
        
    <div class="buttons">
            <button id="upload-btn" onclick="document.getElementById('upload-button').click()" class="btn btn-dark">upload image</button>
            <form class="form" action="{% url 'core:index' %}" method ="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <input id="upload-button" name="image" type="file" style="display:none">
                <input id="submit-btn"class="btn btn-dark" value="Scan image....." type="submit">
            </form>
    </div>  
    
{% if image%}
<div class=" abc">
        <img  id="scanned-image" src="data:image/png;base64, {{image}}">
</div>
{% endif %}

{% if ocr%}
<div id="scanned-text" >
    {{ocr}}
</div>
{% endif %}

    
</body>
</html> 